Script "stack_NestedDGBehavior_button_id_1047"

/*
# Name: button "InlineDGBehavior" of card id 1002 of stack "NestedDGBehavior"
# ID: button id 1047 of card id 1002 of stack "NestedDGBehavior"
# Behavior: button id 1005 of stack "revDataGridLibrary"
*/


on mouseDoubleUp pButtonNumber
   put the long name of the target & cr & the long name of me & cr & the long name of this me   
end mouseDoubleUp
